services:
  frontend:
    build:
      context: frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ThePassword
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
volumes:
  data:
