services:
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db-users
      - db-logs
  db-users:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data-users:/data/db
  db-logs:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - data-logs:/data
volumes:
  data-users:
  data-logs:
